### ISSUE TITLE
Clave privada en repositorio (localhost.key)

### ISSUE THREAD

**Issue by cybercamphackathon** [JunquerGJ/Atlas#2]
Se ha encontrado una clave privada en el repositorio de código, lo no es una buena práctica. Sería recomendable rotar la clave y añadir una linea al `.gitignore` para evitar añadir `*.key` o incluso `*.cert` en el futuro.

https://github.com/JunquerGJ/Atlas/blob/master/localhost.key

**Comment by hedesil** [comment]
Eliminadas claves y certificados. Estamos añadiéndolo al fichero .gitignore para el próximo push.
