### ISSUE TITLE
Secrets stored in repository

### ISSUE THREAD

**Issue by cybercamphackathon** [JunquerGJ/Atlas#3]
https://github.com/JunquerGJ/Atlas/blob/master/.env

You may want to include this file in the .gitignore file, so it isn't commited in the code repository.
Please change all the credentials shown in this file, since they have been exposed.

**Comment by hedesil** [comment]
We deleted all sensitive content from the file. In the productive version (docker and amazon) we use a ENV config file in the EC2 instance, but this file is usefull for us in develoment environment. 
Can we still having this file without sensitive content or we should delete it?

**Comment by hedesil** [comment]
Fixed and file .env added to .gitignore in revission 99da507705c20b9b3f19e318a2cde3f216c46759
