### ISSUE TITLE
Secrets in console/log

### ISSUE THREAD

**Issue by cybercamphackathon** [JunquerGJ/Atlas#4]
It isn't considered a good security practice to print secrets in the console log.
That information could be stored in plan text files in an insecure way.
I'm sharing an example, but I have seen more of them across the code. Please fix all of them:
https://github.com/JunquerGJ/Atlas/blob/2747029330a0898232c9f45f3559adcac0d4dbb5/src/routes/jira/jira.service.ts#L58

**Comment by hedesil** [comment]
Deleted consoles.log() with oauth secrets in commit b8d918bd (currently merged with master). Can we delete original branch now?
